# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YellowPop' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YellowPop
  pod 'TPKeyboardAvoiding'

  target 'YellowPopTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YellowPopUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
